version: "0.1"
services: 
  db:
    build: ./mysql
    container_name: db
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/var/log/mysql
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: liushuaicai
      MYSQL_USER: lsc
      MYSQL_PASSWORD: liushuaicai
    restart: always
  php:
    build: ./php-fpm
    container_name: php
    volumes: 
      # - /Users/liushuaicai/PhpstormProjects/jiajiao.mubiao.online:/www/web/jiajiao.mubiao.online
      # - /Users/liushuaicai/PhpstormProjects/jwt1.lsc.com:/www/web/jwt1.lsc.com
      # - /Users/liushuaicai/PhpstormProjects/jwt2.lsc.com:/www/web/jwt2.lsc.com
      - /Users/liushuaicai/PhpstormProjects/rabbit.lsc.com:/www/web/rabbit.lsc.com
      - /Users/liushuaicai/PhpstormProjects/jj.lsc.com:/www/web/jj.lsc.com
      - /Users/liushuaicai/PhpstormProjects/plan.lsc.com:/www/web/plan.lsc.com
      - ./php-fpm/logs:/var/log/php-fpm
      - ./php-fpm/conf/php.ini:/usr/src/php/php.ini
    ports: 
      - "9000:9000"
    links: 
      - db
    restart: always
  nginx:
    build: ./nginx
    container_name: nginx
    volumes: 
      # - /Users/liushuaicai/PhpstormProjects/jiajiao.mubiao.online:/www/web/jiajiao.mubiao.online
      # - /Users/liushuaicai/PhpstormProjects/jwt1.lsc.com:/www/web/jwt1.lsc.com
      # - /Users/liushuaicai/PhpstormProjects/jwt2.lsc.com:/www/web/jwt2.lsc.com
      - /Users/liushuaicai/PhpstormProjects/rabbit.lsc.com:/www/web/rabbit.lsc.com
      - /Users/liushuaicai/PhpstormProjects/jj.lsc.com:/www/web/jj.lsc.com
      - /Users/liushuaicai/PhpstormProjects/plan.lsc.com:/www/web/plan.lsc.com
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
    links: 
      - php
    ports: 
      - "80:80"
    restart: always
  redis:
    build: ./redis
    container_name: redis
    ports: 
      - "6379:6379"
    environment: 
      REDIS_PORT: 6379
    volumes: 
      - ./redis/redis.conf:/etc/redis/redis.conf
      - ./redis/data:/data
    restart: always
    privileged: true
  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    ports: 
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=lsc
      - RABBITMQ_DEFAULT_PASS=123456
    restart: always    
    # volumes: 
    #   - ./rabbitmq/conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #   - ./rabbitmq/conf/enabled_plugins:/etc/rabbitmq/enabled_plugins
  # gitlab:
  #   build: ./gitlab
  #   container_name: gitlab
  #   ports: 
  #     - "443:443"
  #     - "86:80"
  #     - "22:22"
  #   volumes: 
  #     - ./gitlab/config:/etc/gitlab
  #     - ./gitlab/logs:/var/log/gitlab
  #     - ./gitlab/data:/var/opt/gitlab
  #   restart: always
  # gogs:
  #   build: ./gogs
  #   container_name: gogs
  #   # net: backend
  #   ports: 
  #     - "10022:22"
  #     - "10080:3000"
  #   volumes: 
  #     - ./gogs/data:/data
  #   restart: always

  # jenkins:
  #   build: ./jenkins
  #   container_name: jenkins
  #   ports: 
  #     - "8080:8080"
  #     - "50000:50000"
  #   links:
  #     - gogs
  #   volumes: 
  #     - ./jenkins/data:/var/jenkins_home
  #   restart: always

  # memcached:
  #   build: ./memcached
  #   ports: 
  #     - "11211:11211"
  #   container_name: memcached
  #   restart: always