version: "0.1"
services: 
  rabbitmq: 
    image: rabbitmq:management
    container_name: rabbitmq 
    hostname: rabbit
    ports: 
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "15671:15671"
      - "15672:15672"
    environment: 
      - RABBITMQ_DEFAULT_USER=lsc
      - RABBITMQ_DEFAULT_PASS=123456
